GET http://localhost:8080/api/notes

###
POST http://localhost:3001/notes
Content-Type: application/json

{
  "id": 6,
  "text": "Hello we made it",
  "important": true
}

###
DELETE http://localhost:8080/api/notes/65b93a7bb8d6ff2bcba9d507